spring:
  application:
    name: aimed
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/aimed}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/aimed}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  resilience4j:
    retry:
      instances:
        symptomAnalyzerRetry:
          max-attempts: 3
          wait-duration: 200ms
          retry-exceptions:
            - com.fasterxml.jackson.core.JsonProcessingException
          ignore-exceptions:
            - java.lang.IllegalArgumentException
        embeddingRetry:
          max-attempts: 3
          wait-duration: 500ms
          retry-exceptions:
            - org.springframework.web.client.ResourceAccessException
            - org.springframework.web.client.HttpServerErrorException
          ignore-exceptions:
            - org.springframework.web.client.HttpClientErrorException
            - java.lang.IllegalArgumentException
  jwt:
    jwtSecret: ${JWT_SECRET}
    accessExpiration: ${ACCESS_EXP}
    refreshExpiration: ${REFRESH_EXP}
  security:
    clientUrl: http://localhost:3000

ollama:
  url: ${OLLAMA_URL}
  default-model: ${OLLAMA_MODEL}
  default-stream: false
  apiKey: ${OLLAMA_API_KEY}

embedding:
  url: ${EMBEDDING_URL:http://tei:80}

kind: Application