CREATE TYPE INVITATION_STATUS AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TYPE NOTIFICATION_TYPE AS ENUM ('PATIENT', 'DOCTOR');

CREATE TABLE invitations (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    patient_id INT NOT NULL REFERENCES users(id),
    doctor_id INT NOT NULL REFERENCES users(id),
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    status INVITATION_STATUS NOT NULL DEFAULT 'PENDING'::INVITATION_STATUS,
    responded_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE notifications (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    receiver_id INT NOT NULL REFERENCES users(id),
    type NOTIFICATION_TYPE NOT NULL,
    invitation_id INT NOT NULL REFERENCES invitations(id),
    is_read BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TYPE MESSAGE_TYPE ADD VALUE 'INVITATION';

CREATE TABLE invitation_message_payload (
    message_id INT NOT NULL REFERENCES messages(id) PRIMARY KEY,
    content TEXT,
    doctor_data JSONB NOT NULL DEFAULT '{}'::jsonb
);